/**
 * Export-bundle assembler: turns a refinement (structure + dataset + instrument
 * + refined parameters) into the set of files a user drops into FullProf or
 * GSAS-II. Pure — returns `ZipEntry[]`; the UI zips (via zipStore) and downloads.
 *
 * Two program-specific bundles (one click each):
 *  - FullProf: `<name>.pcr` + data (`.dat`/`.int`) + README
 *  - GSAS-II:  `<name>.cif` + `.instprm` (powder) + data (`.xye`/`.hkl`) +
 *              `build_gpx.py` + README
 */

import type { StructureModel } from "@/core/crystal/types";
import type { DiffractionDataset, Radiation } from "@/core/diffraction/types";
import type { InstrumentParameters } from "@/core/diffraction/instrument";
import type { RefinementParameter, ParameterBinding } from "@/core/refinement/types";
import type { ZipEntry } from "@/core/export/zip";
import { structureToCif, type CifRefinementMeta } from "@/core/export/cif";
import { structureToPcr } from "@/core/export/fullprof";
import { instrumentToInstprm, buildGpxScript } from "@/core/export/gsas2";
import { powderDataXye, singleCrystalHkl, singleCrystalInt, radiationWavelength } from "@/core/export/data";

export interface BundleOptions {
  /** Base filename (default: sanitized structure name). */
  readonly name?: string;
  /** Full instrument parameters; derived from the dataset radiation if omitted. */
  readonly instrument?: InstrumentParameters;
  /** Refined parameters + bindings (for CIF value(su) annotation). */
  readonly params?: readonly RefinementParameter[];
  readonly bindings?: readonly ParameterBinding[];
  /** Refinement agreement metadata for the CIF. */
  readonly refinement?: CifRefinementMeta;
  /** Standard BNS label for a magnetic phase. */
  readonly magneticLabel?: string;
}

function isSingleCrystal(dataset: DiffractionDataset): dataset is Extract<DiffractionDataset, { reflections: unknown }> {
  return "reflections" in dataset;
}

/** Filesystem-safe base name. */
function sanitize(name: string): string {
  return name.trim().replace(/[^A-Za-z0-9._-]+/g, "_") || "structure";
}

/** A minimal instrument when the caller doesn't supply full parameters. */
function deriveInstrument(radiation: Radiation): InstrumentParameters {
  if (radiation.kind === "neutron-tof") return { kind: "tof", difC: 0 };
  return {
    kind: "constantWavelength",
    wavelength: radiation.wavelength,
    radiationKind: radiation.kind === "xray" ? "xray" : "neutron",
  };
}

/** FullProf bundle: `.pcr` + data + README. */
export function fullprofBundle(structure: StructureModel, dataset: DiffractionDataset, opts: BundleOptions = {}): ZipEntry[] {
  const name = sanitize(opts.name ?? structure.name);
  const sc = isSingleCrystal(dataset);
  const dataName = `${name}.${sc ? "int" : "dat"}`;
  const data = isSingleCrystal(dataset) ? singleCrystalInt(dataset) : powderDataXye(dataset);
  const wl = radiationWavelength(dataset.radiation);
  const pcr = structureToPcr(structure, { title: name, datFile: dataName, ...(wl ? { wavelength: wl } : {}) });
  return [
    { name: `${name}.pcr`, data: pcr },
    { name: dataName, data },
    { name: "README.txt", data: fullprofReadme(name, sc, dataName) },
  ];
}

/** GSAS-II bundle: `.cif` + `.instprm` (powder) + data + build_gpx.py + README. */
export function gsas2Bundle(structure: StructureModel, dataset: DiffractionDataset, opts: BundleOptions = {}): ZipEntry[] {
  const name = sanitize(opts.name ?? structure.name);
  const sc = isSingleCrystal(dataset);
  const cif = structureToCif(structure, {
    blockName: name,
    ...(opts.params ? { params: opts.params } : {}),
    ...(opts.bindings ? { bindings: opts.bindings } : {}),
    ...(opts.refinement ? { refinement: opts.refinement } : {}),
    ...(opts.magneticLabel ? { magneticLabel: opts.magneticLabel } : {}),
  });
  const dataName = `${name}.${sc ? "hkl" : "xye"}`;
  const data = isSingleCrystal(dataset) ? singleCrystalHkl(dataset) : powderDataXye(dataset);
  const entries: ZipEntry[] = [{ name: `${name}.cif`, data: cif }, { name: dataName, data }];

  let instprmFile: string | undefined;
  if (!sc) {
    instprmFile = `${name}.instprm`;
    entries.push({ name: instprmFile, data: instrumentToInstprm(opts.instrument ?? deriveInstrument(dataset.radiation)) });
  }
  entries.push({
    name: "build_gpx.py",
    data: buildGpxScript({
      gpxName: `${name}.gpx`,
      cifFile: `${name}.cif`,
      phaseName: name,
      dataFile: dataName,
      histogramKind: sc ? "single" : "powder",
      ...(instprmFile ? { instprmFile } : {}),
      ...(sc ? { dataFmthint: "HKLF" } : {}),
    }),
  });
  entries.push({ name: "README.txt", data: gsas2Readme(name, sc, dataName) });
  return entries;
}

function fullprofReadme(name: string, sc: boolean, dataName: string): string {
  return [
    `FullProf bundle for ${name} — generated by MATERIA Workbench.`,
    ``,
    `Files:`,
    `  ${name}.pcr   control + phase (cell, space group, atoms). Open in FullProf/WinPLOTR.`,
    `  ${dataName}   ${sc ? "single-crystal reflections (h k l F² σ)" : "powder data (2θ/TOF, Yobs, esd)"}.`,
    ``,
    `Refined values are written; refinement flags are 0 (a reproducible model).`,
    sc ? `` : `Confirm the data-format code (Ins) in the .pcr matches your FullProf setup.`,
    ``,
  ].join("\n");
}

function gsas2Readme(name: string, sc: boolean, dataName: string): string {
  return [
    `GSAS-II bundle for ${name} — generated by MATERIA Workbench.`,
    ``,
    `Option A — GUI: import ${name}.cif (phase)${sc ? "" : `, ${name}.instprm (instrument)`} and ${dataName} (data).`,
    `Option B — script: run  python build_gpx.py  (needs GSAS-II installed) to`,
    `           assemble ${name}.gpx directly via GSASIIscriptable.`,
    ``,
    `The .gpx is a GSAS-II internal (pickled) project, so it is built by the`,
    `script rather than written directly.`,
    ``,
  ].join("\n");
}
