/**
 * GSAS-II export pieces: the instrument-parameter file (`.instprm`) and the
 * `build_gpx.py` helper that assembles a real `.gpx` via GSASIIscriptable.
 *
 * A `.gpx` is a Python pickle of GSAS-II's internal data tree — impractical and
 * version-fragile to hand-write — so we emit the files GSAS-II *imports* (CIF
 * phase via the existing cif.ts, this `.instprm`, and data) plus a tiny script
 * that builds the `.gpx` with the official scriptable API. Script verified
 * against the GSASIIscriptable source (G2Project / add_phase /
 * add_powder_histogram / add_single_histogram / save signatures).
 *
 * The `.instprm` header warns "do not add/delete items!", so each instrument
 * Type emits exactly the key set GSAS-II expects (PXC / PNC / PNT), matching the
 * bundled instrument files. Pure string producers; saving/zipping are UI.
 */

import type { InstrumentParameters } from "@/core/diffraction/instrument";

const INSTPRM_HEADER = "#GSAS-II instrument parameter file; do not add/delete items!";

/** Serialize an instrument to a GSAS-II `.instprm`. */
export function instrumentToInstprm(inst: InstrumentParameters): string {
  const rows: Array<[string, number | string]> =
    inst.kind === "tof" ? tofRows(inst) : cwRows(inst);
  return [INSTPRM_HEADER, ...rows.map(([k, v]) => `${k}:${v}`)].join("\n") + "\n";
}

function cwRows(inst: Extract<InstrumentParameters, { kind: "constantWavelength" }>): Array<[string, number | string]> {
  const xray = inst.radiationKind !== "neutron";
  // PXC (X-ray CW) and PNC (neutron CW) share the profile keys; PXC adds
  // Polariz. and Source. Peak-shape terms default to 0 (refined in GSAS-II).
  const rows: Array<[string, number | string]> = [
    ["Type", xray ? "PXC" : "PNC"],
    ["Bank", 1.0],
    ["Lam", inst.wavelength],
    ["Zero", inst.zero ?? 0],
  ];
  if (xray) rows.push(["Polariz.", inst.polarization ?? 0.7]);
  rows.push(
    ["U", inst.u ?? 0],
    ["V", inst.v ?? 0],
    ["W", inst.w ?? 0],
    ["X", inst.x ?? 0],
    ["Y", inst.y ?? 0],
    ["Z", 0],
    ["SH/L", 0.002],
    ["Azimuth", 0.0],
  );
  if (xray) rows.push(["Source", ""]);
  return rows;
}

function tofRows(inst: Extract<InstrumentParameters, { kind: "tof" }>): Array<[string, number | string]> {
  // PNT (neutron TOF): the full back-to-back-exponential + Gaussian σ key set
  // GSAS-II expects; difC/difA/difB/Zero come from the model, peak-shape terms
  // default to 0 (refined in GSAS-II).
  return [
    ["Type", "PNT"],
    ["Bank", 1.0],
    ["difC", inst.difC],
    ["difA", inst.difA ?? 0],
    ["difB", inst.difB ?? 0],
    ["Zero", inst.zero ?? 0],
    ["alpha", 0],
    ["beta-0", 0],
    ["beta-1", 0],
    ["beta-q", 0],
    ["sig-0", 0],
    ["sig-1", 0],
    ["sig-2", 0],
    ["sig-q", 0],
    ["X", 0],
    ["Y", 0],
    ["Z", 0],
    ["2-theta", 90.0],
    ["fltPath", 0],
    ["Azimuth", 0.0],
  ];
}

export interface GpxScriptOptions {
  /** Output project filename, e.g. "MnO.gpx". */
  readonly gpxName: string;
  /** CIF phase file in the bundle. */
  readonly cifFile: string;
  /** Phase name for GSAS-II. */
  readonly phaseName: string;
  /** Data file in the bundle. */
  readonly dataFile: string;
  /** `.instprm` file (powder only). */
  readonly instprmFile?: string;
  /** Powder or single-crystal histogram. */
  readonly histogramKind: "powder" | "single";
  /** Optional importer format hint for the data file (else GSAS-II auto-detects). */
  readonly dataFmthint?: string;
}

/**
 * Generate a `build_gpx.py` that assembles a `.gpx` from the bundle files via
 * GSASIIscriptable. Signatures verified against the GSAS-II source.
 */
export function buildGpxScript(opts: GpxScriptOptions): string {
  const q = (s: string) => `'${s.replace(/'/g, "\\'")}'`;
  const hint = opts.dataFmthint ? `, fmthint=${q(opts.dataFmthint)}` : "";
  const lines: string[] = [
    "#!/usr/bin/env python",
    '"""Assemble a GSAS-II project (.gpx) from this bundle.',
    "",
    "Requires GSAS-II installed (https://gsas-ii.readthedocs.io).",
    "Run from this folder:  python build_gpx.py",
    "Generated by MATERIA Workbench.",
    '"""',
    "try:",
    "    from GSASII import GSASIIscriptable as G2sc",
    "except ImportError:  # older installs expose it on the path directly",
    "    import GSASIIscriptable as G2sc",
    "",
    `gpx = G2sc.G2Project(newgpx=${q(opts.gpxName)})`,
    `phase = gpx.add_phase(${q(opts.cifFile)}, phasename=${q(opts.phaseName)}, fmthint='CIF')`,
  ];
  if (opts.histogramKind === "single") {
    lines.push(`gpx.add_single_histogram(${q(opts.dataFile)}, phase=phase${hint})`);
  } else {
    const iparams = opts.instprmFile ? `, ${q(opts.instprmFile)}` : "";
    lines.push(`gpx.add_powder_histogram(${q(opts.dataFile)}${iparams}, phases=[phase]${hint})`);
  }
  lines.push("gpx.save()", `print('Wrote ${opts.gpxName}')`);
  return lines.join("\n") + "\n";
}
