import { describe, it, expect } from "vitest";
import type { StructureModel, AtomSite, UnitCell } from "@/core/crystal/types";
import type { PdfPattern } from "@/core/diffraction/types";
import { IDENTITY3 } from "@/core/math/mat3";
import { refine } from "@/core/refinement/engine";
import { buildPdfProblem, buildPdfSpec, buildMultiPhasePdfProblem, buildMultiPhasePdfSpec } from "@/core/workflow/pdf";
import { PDFFIT2_GOLDEN, type Pdffit2GoldenCase } from "@/core/pdf/pdffit2Golden";

/**
 * External-reference gates against the real PDFfit2 engine (the calculator
 * inside PDFgui): curve-level agreement of the full terminated forward model,
 * and a refined-parameter recovery from PDFfit2-generated observations. The
 * fixture is generated by running diffpy.pdffit2 locally (see pdffit2Golden.ts)
 * and committed, so these gates run everywhere including CI.
 */

const IDENTITY_OP = { rotation: IDENTITY3, translation: [0, 0, 0] as const, xyz: "x,y,z" };

function p1Structure(
  id: string,
  a: number,
  siteRows: readonly (readonly [string, number, number, number, number])[],
  uScale = 1,
): StructureModel {
  const cell: UnitCell = { a, b: a, c: a, alpha: 90, beta: 90, gamma: 90 };
  const sites: AtomSite[] = siteRows.map(([el, x, y, z, u], i) => ({
    label: `${el}${i + 1}`,
    element: el,
    position: [x, y, z],
    occupancy: 1,
    adp: { kind: "isotropic", bIso: 8 * Math.PI * Math.PI * u * uScale },
  }));
  return { id, name: id, cell, spaceGroup: { operations: [IDENTITY_OP] }, sites };
}

function structureFor(c: Pdffit2GoldenCase, aOverride?: number, uScale = 1): StructureModel {
  if (c.ops && c.sitesAniso) {
    // Symmetric case: MATERIA expands the asymmetric unit over the space-group
    // operations itself — positions AND rotated anisotropic tensors — while the
    // reference g came from diffpy's own independent expansion.
    const a = aOverride ?? c.a;
    const cell: UnitCell = { a, b: a, c: c.c ?? a, alpha: 90, beta: 90, gamma: 90 };
    const operations = c.ops.map((op, i) => ({
      rotation: op.r as unknown as [[number, number, number], [number, number, number], [number, number, number]],
      translation: [op.t[0]!, op.t[1]!, op.t[2]!] as [number, number, number],
      xyz: `op${i}`,
    }));
    const sites: AtomSite[] = c.sitesAniso.map(([el, x, y, z, u], i) => ({
      label: `${el}${i + 1}`,
      element: el,
      position: [x, y, z],
      occupancy: 1,
      adp: { kind: "anisotropic", uAniso: [u[0]!, u[1]!, u[2]!, u[3]!, u[4]!, u[5]!] },
    }));
    return { id: "g", name: c.name, cell, spaceGroup: { operations }, sites };
  }
  return p1Structure(c.name, aOverride ?? c.a, c.sites, uScale);
}

function patternFor(c: Pdffit2GoldenCase): PdfPattern {
  const step = (c.rmax - c.rmin) / (c.n - 1);
  return {
    id: c.name,
    name: c.name,
    scatteringType: c.scatteringType,
    points: c.g.map((g, i) => ({ r: c.rmin + i * step, gObs: g })),
    qmax: c.qmax,
    qdamp: c.qdamp,
    qbroad: c.qbroad,
  };
}

/** MATERIA's calculated curve at the golden's own parameters (single- or
 *  two-phase, with the case's δ2/spdiameter/phase-2 scale applied). */
function materiaCurve(c: Pdffit2GoldenCase): Float64Array {
  const pattern = patternFor(c);
  if (c.sites2 && c.a2 !== undefined) {
    const a = { ...p1Structure("phase1", c.a, c.sites), id: "phase1" };
    const b = { ...p1Structure("phase2", c.a2, c.sites2), id: "phase2" };
    const spec = buildMultiPhasePdfSpec([a, b], pattern);
    const params = spec.params.map((p) => {
      if (p.kind === "delta2") return { ...p, value: c.delta2 };
      if (p.id === "p1_pdfScale") return { ...p, value: c.scale2 ?? 1 };
      return p;
    });
    const problem = buildMultiPhasePdfProblem(spec.phases, pattern, params, spec.bindings);
    const values: Record<string, number> = {};
    for (const p of params) values[p.id] = p.value;
    return problem.calculate(values);
  }
  const structure = structureFor(c);
  const spec = buildPdfSpec(structure, pattern);
  const params = spec.params.map((p) => {
    if (p.id === "delta2") return { ...p, value: c.delta2 };
    if (p.id === "spdiameter" && c.spdiameter !== undefined) return { ...p, value: c.spdiameter };
    return p;
  });
  const problem = buildPdfProblem(structure, pattern, params, spec.bindings);
  const values: Record<string, number> = {};
  for (const p of params) values[p.id] = p.value;
  return problem.calculate(values);
}

describe.each(PDFFIT2_GOLDEN.map((c) => [c.name, c] as const))("PDFfit2 golden — %s", (_name, c) => {
  it("reproduces the reference curve (terminated, enveloped, δ2-sharpened)", () => {
    const mine = materiaCurve(c);
    let num = 0;
    let denM = 0;
    let denG = 0;
    let maxAbs = 0;
    let peak = 0;
    for (let i = 0; i < c.g.length; i++) {
      const d = mine[i]! - c.g[i]!;
      num += mine[i]! * c.g[i]!;
      denM += mine[i]! * mine[i]!;
      denG += c.g[i]! * c.g[i]!;
      maxAbs = Math.max(maxAbs, Math.abs(d));
      peak = Math.max(peak, Math.abs(c.g[i]!));
    }
    const corr = num / Math.sqrt(denM * denG);
    const kappa = num / denM;
    const relRms = Math.sqrt(
      c.g.reduce((s, g, i) => s + (mine[i]! - g) ** 2, 0) / denG,
    );
    // eslint-disable-next-line no-console
    console.log(`[pdffit2:${c.name}] corr=${corr.toFixed(5)} κ=${kappa.toFixed(4)} relRMS=${relRms.toFixed(4)} max|Δ|/peak=${(maxAbs / peak).toFixed(4)}`);
    expect(corr).toBeGreaterThan(0.999);
    // Neutron cases containing Mn: PDFfit2's b table has Mn −3.75018 / O 5.8054
    // vs our NIST Sears values Mn −3.73 / O 5.803. ⟨b⟩ nearly cancels for MnO,
    // so that last-digit provenance difference amplifies to a ~2.3 % amplitude
    // (κ) offset — a documented table difference, not a model error (the shape
    // agreement stays at corr > 0.9998). Measured κ = 1.0226; gate at 1.035.
    const hasMnNeutron =
      c.scatteringType === "neutron" &&
      [...c.sites, ...(c.sites2 ?? [])].some(([el]) => el === "Mn");
    const kappaMax = hasMnNeutron ? 1.035 : 1.02;
    expect(kappa).toBeGreaterThan(0.98);
    expect(kappa).toBeLessThan(kappaMax);
    expect(relRms).toBeLessThan(0.05);
  });
});

describe("PDFfit2 refined-parameter recovery (P1 gate)", () => {
  // Per-case allowances with a physical reason, not slack:
  //  - mno_neutron: the b-table provenance offset (see the curve gate) is a
  //    near-pure amplitude effect, absorbed by pdfScale ≈ 1.023.
  //  - mno_xray: oxygen (Z = 8) is a weak X-ray scatterer next to Mn (Z = 25) —
  //    its U is genuinely ill-determined from X-ray data alone, the classic
  //    light-element limitation; only Mn's ADP is gated tightly.
  //  - mno_neutron bTol 0.2: the Mn b offset (−3.75 vs −3.73) is not a pure
  //    amplitude effect — pair-class weights shift relative to each other and
  //    the residual lands in the per-element ADPs, hardest on Mn whose b² is
  //    2.4× smaller than O's. Measured worst case 13.4 %.
  const CASES: readonly (readonly [string, { scaleLo: number; scaleHi: number; bTol: number; weakElement?: string }])[] = [
    ["ni_neutron", { scaleLo: 0.97, scaleHi: 1.03, bTol: 0.1 }],
    ["mno_neutron", { scaleLo: 0.97, scaleHi: 1.05, bTol: 0.2 }],
    ["mno_xray", { scaleLo: 0.97, scaleHi: 1.03, bTol: 0.1, weakElement: "O" }],
  ];
  it.each(CASES)("%s: refining a perturbed model recovers the reference truth", (name, tol) => {
    const c = PDFFIT2_GOLDEN.find((g) => g.name === name)!;
    // Perturb: cell +0.5 %, U ×1.5; δ2 held at the reference value.
    const structure = structureFor(c, c.a * 1.005, 1.5);
    const pattern = patternFor(c);
    const spec = buildPdfSpec(structure, pattern);
    const params = spec.params.map((p) => {
      if (p.id === "delta2") return { ...p, value: c.delta2 };
      if (p.kind === "bIso") return { ...p, fixed: false };
      if (p.kind === "cellAngle") return { ...p, fixed: true };
      return { ...p };
    });
    const problem = buildPdfProblem(structure, pattern, params, spec.bindings, spec.restraints, { min: 1.0 });
    const result = refine(problem, { maxIterations: 50, convergenceTolerance: 1e-10 });
    expect(result.status).toBe("converged");
    const aId = params.find((p) => p.kind === "cellLength")!.id;
    expect(Math.abs(result.parameters[aId]! - c.a)).toBeLessThan(2e-3);
    expect(result.parameters["pdfScale"]!).toBeGreaterThan(tol.scaleLo);
    expect(result.parameters["pdfScale"]!).toBeLessThan(tol.scaleHi);
    // Recovered ADPs vs the reference, per element (weak scatterers exempt).
    for (const p of params.filter((q) => q.kind === "bIso")) {
      if (tol.weakElement && p.label.includes(tol.weakElement)) continue;
      const refB = spec.params.find((q) => q.id === p.id)!.value / 1.5;
      expect(Math.abs(result.parameters[p.id]! - refB) / refB).toBeLessThan(tol.bTol);
    }
    // eslint-disable-next-line no-console
    console.log(`[pdffit2:refit:${name}] a=${result.parameters[aId]!.toFixed(5)} (ref ${c.a}) scale=${result.parameters["pdfScale"]!.toFixed(4)} Rw=${((result.agreement.rWeighted ?? 0) * 100).toFixed(2)}%`);
  });
});
