/**
 * External golden: pystog's S(Q) → G(r) (ORNL's Python port of RMCProfile's
 * StoG) — the transformed VALUES and the propagated UNCERTAINTY, for the four
 * option combinations. Fixture generated by scripts/gen_pystog_golden.py.
 *
 * Values agree to rounding. Uncertainties differ by two DOCUMENTED,
 * exactly-quantified convention choices, and the test reconciles both rather
 * than loosening a tolerance:
 *
 *  1. pystog integrates the VARIANCE with its own trapezoid,
 *     Σ_i ΔQ²·(e_i + e_{i+1})/2 with e = (M·σ_F·sin Qr)², which weights the two
 *     endpoint terms by ½ΔQ². The exact variance of the trapezoid VALUE is
 *     Σ_k w_k²·e_k, endpoint weight ¼ΔQ² (w = ΔQ/2 there). On a uniform grid
 *     the difference is exactly (2/π)²·(ΔQ²/4)·(e_first + e_last).
 *  2. pystog's error ignores the omitted-low-Q correction, which is built from
 *     the first measured S(Q_0) and so carries its error; ours propagates it.
 *     With the correction on, pystog's dG equals its dG without it, while ours
 *     grows by exactly node 0's extra column term.
 */
import { describe, it, expect } from "vitest";
import { PYSTOG_GOLDEN, PYSTOG_VERSION } from "@/core/totalscattering/pystogGolden";
import {
  fOfQFromSOfQ,
  lorchModification,
  sigmaFFromSigmaS,
  sineTransform,
  sineTransformOperator,
  type SineTransformOptions,
} from "@/core/totalscattering/fourier";

const SHELLS = [[2.5, 0.6, 0.006], [3.6, 0.45, 0.009], [4.4, 0.35, 0.011]] as const;
/** Must match toy_sofq() in scripts/gen_pystog_golden.py operation for operation. */
function toySofQ(q: number): number {
  let s = 1;
  for (const [d, n, u] of SHELLS) s = s + ((n * Math.sin(q * d)) / (q * d)) * Math.exp(-0.5 * u * q * q * d);
  return s;
}

const q = Array.from({ length: 1181 }, (_, k) => 0.4 + 0.02 * k);
const r = Array.from({ length: 200 }, (_, j) => 0.1 * (j + 1));
const sq = q.map(toySofQ);
const dsq = q.map((x) => 0.002 * (1 + 0.15 * x));
const f = fOfQFromSOfQ(q, sq);
const sigmaF = sigmaFFromSigmaS(q, dsq);

const CASES: readonly [keyof typeof PYSTOG_GOLDEN, SineTransformOptions][] = [
  ["plain", {}],
  ["lorch", { modification: "lorch" }],
  ["lowq", { lowQ: "linear" }],
  ["lorch_lowq", { modification: "lorch", lowQ: "linear" }],
];

describe(`pystog ${PYSTOG_VERSION} golden — S(Q) → G(r) with propagated dG`, () => {
  for (const [name, opts] of CASES) {
    it(`${name}: G(r) matches to rounding`, () => {
      const ref = PYSTOG_GOLDEN[name];
      const ours = sineTransform(sineTransformOperator(q, opts), f, r).g;
      const scale = Math.max(...ref.g.map(Math.abs));
      for (let j = 0; j < r.length; j++) expect(Math.abs(ours[j]! - ref.g[j]!)).toBeLessThan(1e-12 * scale);
    });
  }

  for (const [name, opts] of CASES.filter(([n]) => n === "plain" || n === "lorch")) {
    it(`${name}: σ_G matches once pystog's endpoint variance weights (½ΔQ² vs the exact ¼ΔQ²) are reconciled`, () => {
      const ref = PYSTOG_GOLDEN[name];
      const op = sineTransformOperator(q, opts);
      const ours = sineTransform(op, f, r, sigmaF).sigma!;
      const dq = 0.02;
      const last = q.length - 1;
      const m = (k: number): number => (opts.modification === "lorch" ? lorchModification(q[k]!, op.qmax) : 1);
      let worstRaw = 0;
      for (let j = 0; j < r.length; j++) {
        const e = (k: number): number => (m(k) * sigmaF[k]! * Math.sin(q[k]! * r[j]!)) ** 2;
        const endpointExcess = (2 / Math.PI) ** 2 * (dq * dq / 4) * (e(0) + e(last));
        const reconciled = Math.sqrt(ref.dg[j]! ** 2 - endpointExcess);
        expect(Math.abs(ours[j]! - reconciled)).toBeLessThan(1e-12 * ref.dg[j]!);
        worstRaw = Math.max(worstRaw, Math.abs(ours[j]! / ref.dg[j]! - 1));
      }
      // The convention difference is real but small: an O(1/N_Q) endpoint
      // effect, dominated by the high-Q end where Q²σ² is largest — which Lorch
      // zeroes (M(Qmax) = 0), leaving only the tiny low-Q endpoint term.
      expect(worstRaw).toBeLessThan(2e-3);
      if (name === "plain") expect(worstRaw).toBeGreaterThan(1e-4);
      else expect(worstRaw).toBeLessThan(1e-6);
    });
  }

  it("low-Q cases: pystog's dG ignores the extrapolation; ours adds exactly node 0's extra column", () => {
    expect(PYSTOG_GOLDEN.lowq.dg).toEqual(PYSTOG_GOLDEN.plain.dg);
    expect(PYSTOG_GOLDEN.lorch_lowq.dg).toEqual(PYSTOG_GOLDEN.lorch.dg);
    for (const mod of ["none", "lorch"] as const) {
      const without = sineTransform(sineTransformOperator(q, { modification: mod }), f, r, sigmaF).sigma!;
      const opLow = sineTransformOperator(q, { modification: mod, lowQ: "linear" });
      const withLow = sineTransform(opLow, f, r, sigmaF).sigma!;
      // Node 0's column: c_0·sin(Q_0 r) + e(r), e = ∂G_low/∂F_0, read off the
      // VALUE path as G_low(F_0 + 1) − G_low(F_0) (G_low is linear in F_0).
      const bump = Float64Array.from(f);
      bump[0] = bump[0]! + 1;
      const g1 = sineTransform(opLow, bump, r).g;
      const g0 = sineTransform(opLow, f, r).g;
      const c0s = (j: number): number => opLow.coef[0]! * Math.sin(q[0]! * r[j]!);
      for (let j = 0; j < r.length; j++) {
        const col = g1[j]! - g0[j]!;
        const expected = without[j]! ** 2 + sigmaF[0]! ** 2 * (col * col - c0s(j) ** 2);
        expect(withLow[j]! ** 2).toBeCloseTo(expected, 14);
      }
    }
  });
});
