#!/usr/bin/env python3
"""Generate the built-in 230 space-group operation table from gemmi.

gemmi ships the validated International Tables space-group settings. For each of
the 230 standard settings we emit the full general-position operation list as
Jones-Faithful triplets (the same format parseSymmetryOperation reads). The
operations are the trustworthy source of truth the refinement engine's symmetry
depends on (systematic absences, site symmetry, point group, multiplicity).

Usage:  python3 scripts/gen_space_groups.py > src/core/crystal/spaceGroupData.ts
Requires:  python3 -m pip install gemmi
"""
import sys
import gemmi


def main() -> None:
    out = sys.stdout
    out.write("/**\n")
    out.write(" * GENERATED by scripts/gen_space_groups.py from gemmi — DO NOT EDIT.\n")
    out.write(" *\n")
    out.write(" * The 230 space groups (standard ITA setting), each as its full list of\n")
    out.write(" * general-position symmetry operations in Jones-Faithful (xyz) form. gemmi is\n")
    out.write(" * the reference; regenerate rather than hand-editing.\n")
    out.write(" */\n\n")
    out.write("export interface SpaceGroupData {\n")
    out.write("  readonly number: number;\n")
    out.write("  readonly hm: string;\n")
    out.write("  readonly ops: readonly string[];\n")
    out.write("}\n\n")
    out.write("export const SPACE_GROUP_DATA: readonly SpaceGroupData[] = [\n")
    for n in range(1, 231):
        sg = gemmi.SpaceGroup(n)
        ops = [op.triplet() for op in sg.operations()]
        hm = sg.hm.strip()
        ops_str = ",".join('"%s"' % o for o in ops)
        out.write('  { number: %d, hm: "%s", ops: [%s] },\n' % (n, hm, ops_str))
    out.write("];\n")


if __name__ == "__main__":
    main()
