#!/usr/bin/env python3
"""Generate the built-in space-group setting table from gemmi.

gemmi ships the validated International Tables settings: all 564 entries of
`gemmi.spacegroup_table()` at gemmi 0.7.3 — every number in every tabulated
setting (both origin choices of the 24 groups that have two, hexagonal and
rhombohedral axes for the 7 R groups, the monoclinic unique-axis/cell choices,
the orthorhombic axis permutations). For each setting we emit its H-M symbol,
setting suffix, Hall symbol, short symbol, whether it is gemmi's reference
setting for the number, and the full general-position operation list as
Jones-Faithful triplets (the format parseSymmetryOperation reads).

The table records settings; it does not choose one. A symbol shared by several
settings ("F d -3 m" is origin choice 1 or 2) is resolved by spaceGroups.ts
only from explicit information (a setting suffix, a Hall symbol, the cell for
H/R axes) and is an error otherwise.

Usage:  python3 scripts/gen_space_groups.py > src/core/crystal/spaceGroupData.ts
Requires:  python3 -m pip install gemmi==0.7.3
"""
import json
import sys

import gemmi

GEMMI_VERSION = "0.7.3"
N_SETTINGS = 564


def main() -> None:
    if gemmi.__version__ != GEMMI_VERSION:
        sys.exit(f"gemmi {gemmi.__version__} found; this table is pinned to gemmi {GEMMI_VERSION}")
    table = list(gemmi.spacegroup_table())
    if len(table) != N_SETTINGS:
        sys.exit(f"expected {N_SETTINGS} settings, gemmi has {len(table)}")
    references = [sg for sg in table if sg.is_reference_setting()]
    if sorted(sg.number for sg in references) != list(range(1, 231)):
        sys.exit("expected exactly one reference setting per space-group number")

    out = sys.stdout
    out.write("/**\n")
    out.write(" * GENERATED by scripts/gen_space_groups.py from gemmi " + GEMMI_VERSION + " — DO NOT EDIT.\n")
    out.write(" *\n")
    out.write(" * All " + str(N_SETTINGS) + " space-group settings of gemmi.spacegroup_table(), each with its\n")
    out.write(" * full list of general-position symmetry operations in Jones-Faithful (xyz)\n")
    out.write(" * form. `reference` marks gemmi's reference setting for the number (origin\n")
    out.write(" * choice 2, hexagonal axes, unique axis b). gemmi is the reference;\n")
    out.write(" * regenerate rather than hand-editing.\n")
    out.write(" */\n\n")
    out.write("export interface SpaceGroupData {\n")
    out.write("  readonly number: number;\n")
    out.write("  /** Hermann–Mauguin symbol without the setting suffix, e.g. \"F d -3 m\". */\n")
    out.write("  readonly hm: string;\n")
    out.write("  /** Setting suffix: \"1\"/\"2\" origin choice, \"H\"/\"R\" axes, \"\" when unique. */\n")
    out.write("  readonly ext: string;\n")
    out.write("  /** Hall symbol. */\n")
    out.write("  readonly hall: string;\n")
    out.write("  /** Short symbol, e.g. \"P21/c\", \"P1121/a\", \"Fd-3m\". */\n")
    out.write("  readonly short: string;\n")
    out.write("  /** gemmi's reference setting for this number (exactly one per number). */\n")
    out.write("  readonly reference: boolean;\n")
    out.write("  readonly ops: readonly string[];\n")
    out.write("}\n\n")
    out.write("export const SPACE_GROUP_DATA: readonly SpaceGroupData[] = [\n")
    for sg in table:
        ops = ",".join(json.dumps(op.triplet()) for op in sg.operations())
        ext = "" if sg.ext in ("\x00", " ") else sg.ext  # gemmi stores "no suffix" as NUL
        out.write(
            "  { number: %d, hm: %s, ext: %s, hall: %s, short: %s, reference: %s, ops: [%s] },\n"
            % (
                sg.number,
                json.dumps(sg.hm.strip()),
                json.dumps(ext),
                json.dumps(sg.hall.strip()),  # Hall symbols may contain '"'
                json.dumps(sg.short_name()),
                "true" if sg.is_reference_setting() else "false",
                ops,
            )
        )
    out.write("];\n")


if __name__ == "__main__":
    main()
