/**
 * Built-in space-group engine: turn a space-group *number or Hermann–Mauguin
 * symbol* into its full operation list by closing a small set of generators,
 * instead of depending on a CIF to enumerate every equivalent position.
 *
 * Why this exists (Roadmap F2). The symmetry-constraint machinery
 * (`siteConstraints`, `adpConstraints`, `allowedMoments`, `cellConstraints`) is
 * correct but is only ever as good as the operation list it is handed. When that
 * list comes straight from a CIF it may be incomplete, non-standard, or absent —
 * so the constraints derived from it inherit those gaps. A generator-based engine
 * gives a *canonical, complete* operation set keyed by the International Tables
 * number, which is the trustworthy foundation robust refinement needs.
 *
 * Theory. A space group is generated by a handful of operations; composing them
 * (and their products) until no new operation appears yields the whole group —
 * the standard orbit/closure construction. Centring translations are ordinary
 * generators here (rotation = I, translation = the centring vector), so an
 * F-centred group is just its point-group cosets × the four centring cosets.
 *
 * Scope. The generated table holds all 564 settings gemmi tabulates (every
 * number in every ITA setting: origin choices, H/R axes, monoclinic and
 * orthorhombic settings). {@link resolveSpaceGroupSetting} maps a number,
 * symbol or Hall symbol to exactly one of them, or throws.
 */

import type { SpaceGroup, SymmetryOperation, UnitCell } from "@/core/crystal/types";
import type { Vec3 } from "@/core/math/types";
import { SPACE_GROUP_DATA, type SpaceGroupData } from "@/core/crystal/spaceGroupData";
import { composeOperations, operationKey, parseSymmetryOperation } from "@/core/crystal/symmetry";
import { wrapFractional } from "@/core/math/vec3";

/** A hard cap on closure size: no standard space group exceeds 192 general
 *  positions, so overshooting means the generators are wrong (or non-crystallo-
 *  graphic) and we should fail loudly rather than loop forever. */
const MAX_GROUP_ORDER = 768;

const IDENTITY: SymmetryOperation = parseSymmetryOperation("x,y,z");

/** Wrap an operation's translation into [0, 1) so equal cosets share a key. */
function normalizeTranslation(op: SymmetryOperation): SymmetryOperation {
  return { ...op, translation: wrapFractional(op.translation) };
}

/**
 * Close a set of generators into the full group: seed with the identity and the
 * generators, then repeatedly compose every pair until the set stops growing.
 * Operations are deduplicated modulo lattice translation via `operationKey`.
 * Throws if the set exceeds {@link MAX_GROUP_ORDER} (a sign of bad generators).
 *
 * Idempotent on an already-complete group: closing a full operation list returns
 * an equivalent full list.
 */
export function expandGenerators(
  generators: readonly SymmetryOperation[],
  maxOrder: number = MAX_GROUP_ORDER,
): SymmetryOperation[] {
  const byKey = new Map<string, SymmetryOperation>();
  byKey.set(operationKey(IDENTITY), IDENTITY);
  for (const g of generators) {
    const n = normalizeTranslation(g);
    byKey.set(operationKey(n), n);
  }

  let changed = true;
  while (changed) {
    changed = false;
    const current = [...byKey.values()];
    for (const a of current) {
      for (const b of current) {
        const c = composeOperations(a, b);
        const key = operationKey(c);
        if (!byKey.has(key)) {
          byKey.set(key, c);
          changed = true;
          if (byKey.size > maxOrder) {
            throw new Error(
              `Group closure exceeded ${maxOrder} operations — generators are likely invalid.`,
            );
          }
        }
      }
    }
  }
  return [...byKey.values()];
}

// ── Settings table and strict resolution ───────────────────────────────────
//
// SPACE_GROUP_DATA holds every setting gemmi tabulates (564): both origin
// choices of the 24 groups that have two, hexagonal and rhombohedral axes of
// the 7 R groups, the monoclinic unique-axis/cell choices, the orthorhombic
// axis permutations. A symbol or number that fits several settings is NEVER
// resolved by picking one: "F d -3 m" with origin-2 coordinates expanded with
// origin-1 operations is a silently wrong structure. It resolves only from
// explicit information — a setting suffix (":2", ICSD's "Z"), a Hall symbol, or
// the cell (hexagonal vs rhombohedral axes) — and is an error otherwise.

/** Extended Hermann–Mauguin symbol of a setting: "F d -3 m:2", "R -3 m:H", or
 *  the plain symbol when the setting has no suffix. */
export function extendedSymbol(entry: SpaceGroupData): string {
  return entry.ext ? `${entry.hm}:${entry.ext}` : entry.hm;
}

/** One tabulated setting, as offered to a user who has to choose. */
export interface SpaceGroupSettingInfo {
  readonly number: number;
  /** Extended H-M symbol, e.g. "F d -3 m:2". Resolves to exactly this setting. */
  readonly symbol: string;
  readonly hall: string;
  /** What distinguishes it, e.g. "origin choice 2", "hexagonal axes". */
  readonly description: string;
}

/**
 * A space group that cannot be resolved to exactly one setting: unknown,
 * contradictory, or ambiguous. `candidates` lists the settings the input fits
 * (empty unless the input was ambiguous), so a caller can let the user choose.
 */
export class SpaceGroupSettingError extends Error {
  readonly candidates: readonly SpaceGroupSettingInfo[];
  constructor(message: string, candidates: readonly SpaceGroupSettingInfo[] = []) {
    super(message);
    this.name = "SpaceGroupSettingError";
    this.candidates = candidates;
  }
}

function describeSetting(entry: SpaceGroupData): string {
  switch (entry.ext) {
    case "1": return "origin choice 1";
    case "2": return "origin choice 2";
    case "H": return "hexagonal axes";
    case "R": return "rhombohedral axes";
    default: return entry.reference ? "standard setting" : "non-standard setting";
  }
}

function settingInfo(entry: SpaceGroupData): SpaceGroupSettingInfo {
  return { number: entry.number, symbol: extendedSymbol(entry), hall: entry.hall, description: describeSetting(entry) };
}

/** Normalize a symbol for lookup: drop whitespace, lowercase. */
function normalizeSymbol(symbol: string): string {
  return symbol.replace(/\s+/g, "").toLowerCase();
}
/** Normalize a Hall symbol: its tokens are space-separated and only the lattice
 *  letter is upper case, so collapsing whitespace and lowercasing is lossless. */
function normalizeHall(hall: string): string {
  return hall.trim().replace(/\s+/g, " ").toLowerCase();
}

function addTo<K>(map: Map<K, SpaceGroupData[]>, key: K, entry: SpaceGroupData): void {
  const list = map.get(key);
  if (!list) map.set(key, [entry]);
  else if (!list.includes(entry)) list.push(entry);
}

const BY_NUMBER = new Map<number, SpaceGroupData[]>();
// Four pairs of entries are two spellings of one setting (the e-glide groups:
// "A b a m" = "A c a m", …) and share a Hall symbol, so a Hall symbol maps to
// a list; entries with the same Hall symbol are the same setting.
const BY_HALL = new Map<string, SpaceGroupData[]>();
// Full and short spellings ("P 1 21/c 1", "P21/c", "P1121/a"), then bar-dropped
// fallbacks ("Fm3m") consulted only when no canonical spelling matches, so
// "P3" and "P-3" stay distinct.
const BY_SYMBOL = new Map<string, SpaceGroupData[]>();
const BY_BARLESS = new Map<string, SpaceGroupData[]>();
for (const e of SPACE_GROUP_DATA) {
  addTo(BY_NUMBER, e.number, e);
  addTo(BY_HALL, normalizeHall(e.hall), e);
  for (const spelling of [e.hm, e.short]) {
    addTo(BY_SYMBOL, normalizeSymbol(spelling), e);
    addTo(BY_BARLESS, normalizeSymbol(spelling).replace(/-/g, ""), e);
  }
}

const SUFFIX_TOKEN: Readonly<Record<string, string>> = { S: "1", Z: "2", H: "H", R: "R" };

/**
 * Split an explicit setting off a symbol: "F d -3 m:2", "R -3 m :H", ICSD's
 * trailing "Z"/"S" (origin choice 2/1) and "H"/"R", or "(origin choice 2)".
 */
function splitSettingSuffix(symbol: string): { base: string; ext?: string } {
  const s = symbol.trim();
  let m = /\(\s*origin\s+choice\s*([12])\s*\)$/i.exec(s);
  if (m) return { base: s.slice(0, m.index), ext: m[1]! };
  m = /\(\s*(hexagonal|rhombohedral)\s+(axes|setting)\s*\)$/i.exec(s);
  if (m) return { base: s.slice(0, m.index), ext: m[1]!.toLowerCase() === "hexagonal" ? "H" : "R" };
  m = /\s*:\s*([12HhRr])$/.exec(s);
  if (m) return { base: s.slice(0, m.index), ext: m[1]!.toUpperCase() };
  // A trailing upper-case S/Z/H/R token can never be part of an H-M symbol
  // (only the leading lattice letter is upper case).
  m = /\s+([SZHR])$/.exec(s);
  if (m && s.slice(0, m.index).trim().includes(" ")) return { base: s.slice(0, m.index), ext: SUFFIX_TOKEN[m[1]!]! };
  return { base: s };
}

/** Every setting a Hermann–Mauguin symbol (with or without suffix) names. */
function settingsForSymbol(symbol: string): SpaceGroupData[] {
  const { base, ext } = splitSettingSuffix(symbol);
  const key = normalizeSymbol(base);
  const all = BY_SYMBOL.get(key) ?? BY_BARLESS.get(key.replace(/-/g, "")) ?? [];
  return ext === undefined ? all : all.filter((e) => e.ext === ext);
}

/** The settings a bare IT number names: the reference setting and any setting
 *  sharing its symbol (the other origin choice, or the other axes for R). A
 *  number alone otherwise means the standard setting, e.g. 14 → P 1 21/c 1. */
function settingsForNumber(n: number): SpaceGroupData[] {
  const all = BY_NUMBER.get(n) ?? [];
  const ref = all.find((e) => e.reference);
  return ref ? all.filter((e) => e.hm === ref.hm) : [];
}

const isNear = (x: number, y: number, tol: number): boolean => Math.abs(x - y) <= tol;
const sameLength = (x: number, y: number): boolean => Math.abs(x - y) <= 2e-3 * Math.max(x, y);
function isHexagonalCell(c: UnitCell): boolean {
  return sameLength(c.a, c.b) && isNear(c.alpha, 90, 0.1) && isNear(c.beta, 90, 0.1) && isNear(c.gamma, 120, 0.1);
}
function isRhombohedralCell(c: UnitCell): boolean {
  return sameLength(c.a, c.b) && sameLength(c.b, c.c) && isNear(c.alpha, c.beta, 0.1) && isNear(c.beta, c.gamma, 0.1);
}

/** Hexagonal vs rhombohedral axes are decided by the cell; nothing else is. */
function narrowByCell(pool: SpaceGroupData[], cell: UnitCell | undefined): SpaceGroupData[] {
  if (!cell || !pool.every((e) => e.ext === "H" || e.ext === "R")) return pool;
  const want = isHexagonalCell(cell) ? "H" : isRhombohedralCell(cell) ? "R" : null;
  const narrowed = want ? pool.filter((e) => e.ext === want) : [];
  return narrowed.length > 0 ? narrowed : pool;
}

/**
 * A monoclinic setting fixes which cell angle may differ from 90°; a symbol or
 * number that names the unique-axis-b setting does not describe a cell whose
 * oblique angle is γ. Checked so "P 21/c" with a c-unique cell is an error, not
 * a silently mis-expanded structure.
 */
function checkMonoclinicCell(entry: SpaceGroupData, cell: UnitCell | undefined): void {
  if (!cell || entry.number < 3 || entry.number > 15) return;
  const op = entry.ops.map(parseSymmetryOperation).find((o) => {
    const d = [o.rotation[0][0], o.rotation[1][1], o.rotation[2][2]];
    return d.some((x) => x === 1) && d.some((x) => x === -1);
  });
  if (!op) return;
  const d = [op.rotation[0][0], op.rotation[1][1], op.rotation[2][2]];
  const ones = d.filter((x) => x === 1).length;
  const unique = ones === 1 ? d.indexOf(1) : d.indexOf(-1); // 2-fold: the +1; mirror: the −1
  const angles = [cell.alpha, cell.beta, cell.gamma];
  const oblique = angles.map((x, i) => (Math.abs(x - 90) > 0.1 ? i : -1)).filter((i) => i >= 0);
  if (oblique.length === 1 && oblique[0] !== unique) {
    const axis = "abc"[unique]!;
    const angle = ["α", "β", "γ"][oblique[0]!]!;
    throw new SpaceGroupSettingError(
      `${extendedSymbol(entry)} has unique axis ${axis}, but the cell's oblique angle is ${angle} = ${angles[oblique[0]!]!}°. ` +
        `Give the symmetry operations, a Hall symbol, or the full H-M symbol of the setting.`,
    );
  }
}

/** What the caller knows about a space group: any of number, symbol, Hall. */
export interface SpaceGroupSpec {
  readonly number?: number;
  readonly hermannMauguin?: string;
  readonly hall?: string;
  /**
   * The user's choice among the settings an ambiguous description fits — the
   * extended symbol of one of `SpaceGroupSettingError.candidates`, e.g.
   * "F d -3 m:2". It must be one of the settings the rest of the spec fits;
   * with nothing else given, that is "P 1" alone.
   */
  readonly setting?: string;
}

/**
 * Resolve a space-group description to exactly one tabulated setting, or
 * throw a {@link SpaceGroupSettingError}. Nothing is guessed:
 *  - A Hall symbol names one setting. One not in the table is an error.
 *  - An H-M symbol names every setting that spells it that way; a suffix
 *    (":1"/":2"/":H"/":R", ICSD "S"/"Z"/"H"/"R", "(origin choice 2)") picks one.
 *  - A number alone names its standard setting, or — for the 24 groups with
 *    two origins and the 7 R groups — both standard descriptions.
 *  - Hall, symbol and number must agree; a contradiction is an error.
 *  - Hexagonal vs rhombohedral axes are decided by the cell when given. Two
 *    origin choices are never decided: that needs operations, a Hall symbol,
 *    a suffix, or the user's choice (`error.candidates`).
 *  - No description at all is an error whose one candidate is P 1: the atom
 *    list may be every atom in the cell (diffpy writes such files) or an
 *    asymmetric unit that lost its symmetry, and only the user can say which.
 */
export function resolveSpaceGroupSetting(spec: SpaceGroupSpec, cell?: UnitCell): SpaceGroupData {
  const hall = spec.hall?.trim() || undefined;
  const hm = spec.hermannMauguin?.trim() || undefined;
  let pool: SpaceGroupData[] | null = null;
  if (hall !== undefined) {
    const entries = BY_HALL.get(normalizeHall(hall));
    if (!entries) {
      throw new SpaceGroupSettingError(
        `Hall symbol "${hall}" is not one of the ${BY_HALL.size} tabulated settings; give the symmetry operations instead.`,
      );
    }
    pool = entries;
  }
  if (hm !== undefined) {
    const named = settingsForSymbol(hm);
    if (named.length === 0) {
      // An unrecognized spelling does not override a Hall symbol that resolved.
      if (pool === null) {
        throw new SpaceGroupSettingError(
          `Unknown space group "${hm}". Expected a Hermann–Mauguin symbol (e.g. "P 21/c", "F d -3 m:2"), a Hall symbol, or the symmetry operations.`,
        );
      }
    } else if (pool !== null) {
      const agreed: SpaceGroupData[] = pool.filter((e) => named.includes(e));
      if (agreed.length === 0) {
        throw new SpaceGroupSettingError(
          `Hall symbol "${hall}" (${extendedSymbol(pool[0]!)}) contradicts the H-M symbol "${hm}".`,
        );
      }
      pool = agreed;
    } else {
      pool = named;
    }
  }
  if (spec.number !== undefined) {
    if (!Number.isInteger(spec.number) || spec.number < 1 || spec.number > 230) {
      throw new SpaceGroupSettingError(`Unknown space group number ${spec.number}; expected 1–230.`);
    }
    if (pool !== null) {
      const agreed: SpaceGroupData[] = pool.filter((e) => e.number === spec.number);
      if (agreed.length === 0) {
        throw new SpaceGroupSettingError(
          `Space group number ${spec.number} contradicts ${hall !== undefined ? `Hall symbol "${hall}"` : `"${hm}"`} (No. ${pool[0]!.number}).`,
        );
      }
      pool = agreed;
    } else {
      pool = settingsForNumber(spec.number);
    }
  }
  if (pool === null) {
    const p1 = BY_NUMBER.get(1)![0]!;
    if (spec.setting !== undefined && normalizeSymbol(spec.setting) === normalizeSymbol(extendedSymbol(p1))) return p1;
    const chosen = spec.setting !== undefined ? ` The chosen setting "${spec.setting}" needs a symbol or number to fit; only P 1 can be chosen.` : "";
    throw new SpaceGroupSettingError(
      "No space-group information: no symmetry operations, Hermann–Mauguin symbol, Hall symbol or IT number." +
        `${chosen} If the file lists every atom in the cell, choose P 1.`,
      [{ ...settingInfo(p1), description: "no symmetry: the file lists every atom in the cell" }],
    );
  }
  pool = narrowByCell(pool, cell);
  // Two spellings of one setting are not an ambiguity.
  pool = pool.filter((e, i) => pool!.findIndex((f) => f.hall === e.hall) === i);
  if (spec.setting !== undefined) {
    const want = normalizeSymbol(spec.setting);
    const chosen = pool.filter((e) => normalizeSymbol(extendedSymbol(e)) === want);
    if (chosen.length === 0) {
      throw new SpaceGroupSettingError(
        `The chosen setting "${spec.setting}" is not one the space group fits (${pool.map(extendedSymbol).join(", ")}).`,
        pool.length > 1 ? pool.map(settingInfo) : [],
      );
    }
    pool = chosen;
  }
  if (pool.length > 1) {
    const what = hm !== undefined ? `"${hm}"` : `No. ${spec.number}`;
    const options = pool.map((e) => `${extendedSymbol(e)} (${describeSetting(e)})`).join(", ");
    const hint = pool.every((e) => e.ext === "H" || e.ext === "R")
      ? " The cell is neither hexagonal (a = b, γ = 120°) nor rhombohedral (a = b = c, α = β = γ)."
      : "";
    throw new SpaceGroupSettingError(
      `Space group ${what} is ambiguous: it fits ${options}.${hint} Give the symmetry operations, a Hall symbol, or a setting suffix such as "${extendedSymbol(pool[pool.length - 1]!)}".`,
      pool.map(settingInfo),
    );
  }
  const entry = pool[0]!;
  checkMonoclinicCell(entry, cell);
  return entry;
}

/** The {@link SpaceGroup} for one tabulated setting. */
export function spaceGroupFromSetting(entry: SpaceGroupData): SpaceGroup {
  return {
    number: entry.number,
    hermannMauguin: extendedSymbol(entry),
    operations: entry.ops.map(parseSymmetryOperation),
  };
}

/** True if the number or symbol names at least one tabulated setting
 *  (an ambiguous symbol such as "Fd-3m" counts as known). */
export function isKnownSpaceGroup(id: number | string): boolean {
  if (typeof id === "number") return (BY_NUMBER.get(id)?.length ?? 0) > 0;
  return settingsForSymbol(id).length > 0;
}

/** The reference setting of each of the 230 groups as `{ number,
 *  hermannMauguin }` (for pickers/discovery). */
export function knownSpaceGroups(): { number: number; hermannMauguin: string }[] {
  return SPACE_GROUP_DATA.filter((e) => e.reference).map((e) => ({ number: e.number, hermannMauguin: extendedSymbol(e) }));
}

/** Every tabulated setting (564). */
export function spaceGroupSettings(): SpaceGroupSettingInfo[] {
  return SPACE_GROUP_DATA.map(settingInfo);
}

const opSetKey = (ops: readonly SymmetryOperation[]): string => [...new Set(ops.map(operationKey))].sort().join(";");
const TABLE_OP_KEYS = new Map<SpaceGroupData, string>();

/**
 * The tabulated setting whose operations are exactly `ops` (modulo lattice
 * translations), or undefined when they are no tabulated setting (e.g. an
 * origin-shifted one). Names a structure that carries operations but no
 * symbol, such as one read from a CIF with only a symop loop.
 */
export function settingForOperations(ops: readonly SymmetryOperation[]): SpaceGroupData | undefined {
  const n = new Set(ops.map(operationKey)).size;
  const key = opSetKey(ops);
  return SPACE_GROUP_DATA.find((e) => {
    if (e.ops.length !== n) return false;
    let k = TABLE_OP_KEYS.get(e);
    if (k === undefined) {
      k = opSetKey(e.ops.map(parseSymmetryOperation));
      TABLE_OP_KEYS.set(e, k);
    }
    return k === key;
  });
}

/** A space group's symbol for display and export: its own, else the extended
 *  symbol of the tabulated setting its operations are, else undefined. */
export function spaceGroupSymbol(sg: SpaceGroup): string | undefined {
  if (sg.hermannMauguin) return sg.hermannMauguin;
  const entry = settingForOperations(sg.operations);
  return entry ? extendedSymbol(entry) : undefined;
}

/**
 * Build a {@link SpaceGroup} from an International Tables number or a
 * Hermann–Mauguin symbol (optionally with a setting suffix, e.g. "F d -3 m:2"),
 * using the generated table of all 564 settings. Throws a
 * {@link SpaceGroupSettingError} if the input is unknown or names more than one
 * setting (pass `cell` to let it decide hexagonal vs rhombohedral axes).
 */
export function buildSpaceGroup(id: number | string, cell?: UnitCell): SpaceGroup {
  return spaceGroupFromSetting(
    resolveSpaceGroupSetting(typeof id === "number" ? { number: id } : { hermannMauguin: id }, cell),
  );
}

/**
 * Fractional centering translations implied by a Hermann–Mauguin LATTICE letter
 * (the leading symbol character). These are the copies a CIF may leave implicit,
 * listing only the primitive general positions and relying on the letter for the
 * centring — in which case the centring systematic absences (F: h,k,l all even or
 * all odd; I: h+k+l even; C: h+k even; …) would be missed without adding them.
 *
 * A/B/C/I/F are unambiguous. R is deliberately EXCLUDED: its centring exists only
 * in the hexagonal setting, and telling that apart from a primitive rhombohedral
 * setting needs the setting/origin machinery (roadmap F2.4) — adding hexagonal
 * centring blindly would be a physics error in the rhombohedral setting.
 */
export function latticeCenteringTranslations(hermannMauguin: string): Vec3[] {
  const letter = (hermannMauguin.trim().match(/[A-Za-z]/)?.[0] ?? "P").toUpperCase();
  switch (letter) {
    case "A": return [[0, 0.5, 0.5]];
    case "B": return [[0.5, 0, 0.5]];
    case "C": return [[0.5, 0.5, 0]];
    case "I": return [[0.5, 0.5, 0.5]];
    case "F": return [[0, 0.5, 0.5], [0.5, 0, 0.5], [0.5, 0.5, 0]];
    default: return []; // P, R (setting-dependent), or unknown → no centring added
  }
}

/** Format a centring component (0 or ½) as an xyz-string suffix. */
function half(v: number): string {
  return Math.abs(v - 0.5) < 1e-9 ? "+1/2" : "";
}

/** Centering translations as identity-rotation operations (for group closure). */
function centeringOperations(hermannMauguin: string): SymmetryOperation[] {
  return latticeCenteringTranslations(hermannMauguin).map((t) =>
    parseSymmetryOperation(`x${half(t[0])},y${half(t[1])},z${half(t[2])}`),
  );
}

/**
 * Obverse R-centring operations, but ONLY when the cell is in the HEXAGONAL
 * setting (a=b, α=β=90°, γ=120°). An R group in the primitive rhombohedral
 * setting (a=b=c, α=β=γ) has no centring — which is why F2.2 could not add R
 * centring from the symbol alone; the cell resolves the setting.
 */
function rhombohedralHexCenteringOps(hermannMauguin: string, cell: UnitCell): SymmetryOperation[] {
  const letter = (hermannMauguin.trim().match(/[A-Za-z]/)?.[0] ?? "P").toUpperCase();
  const hexSetting = Math.abs(cell.gamma - 120) < 1 && Math.abs(cell.alpha - 90) < 1 && Math.abs(cell.beta - 90) < 1;
  if (letter !== "R" || !hexSetting) return [];
  return ["x+2/3,y+1/3,z+1/3", "x+1/3,y+2/3,z+2/3"].map(parseSymmetryOperation);
}

/**
 * Ensure a space group has a complete operation list.
 *
 * - If it already carries operations, close them together with the centring
 *   implied by the Hermann–Mauguin lattice letter (a CIF may list only the
 *   primitive general positions, or only a generating subset). Returns the input
 *   unchanged when already complete, so the original objects/ordering are kept.
 *   Explicit operations are authoritative: they fix the setting.
 * - Otherwise build it from the setting table via
 *   {@link resolveSpaceGroupSetting} (number, symbol, optional Hall symbol, and
 *   the cell for hexagonal vs rhombohedral axes, and `options.setting` — the
 *   user's choice among the candidates of an ambiguous description). That THROWS a
 *   {@link SpaceGroupSettingError} for an unknown or ambiguous description, or
 *   for none at all — a structure is never silently expanded in P1 or in a
 *   guessed origin.
 */
export function completeSpaceGroup(
  sg: SpaceGroup,
  cell?: UnitCell,
  options: { readonly hall?: string; readonly setting?: string } = {},
): SpaceGroup {
  if (sg.operations.length > 0) {
    const centering = sg.hermannMauguin
      ? [
          ...centeringOperations(sg.hermannMauguin),
          ...(cell ? rhombohedralHexCenteringOps(sg.hermannMauguin, cell) : []),
        ]
      : [];
    const closed = expandGenerators([...sg.operations, ...centering]);
    return closed.length === sg.operations.length ? sg : { ...sg, operations: closed };
  }
  return spaceGroupFromSetting(
    resolveSpaceGroupSetting(
      {
        ...(sg.number !== undefined ? { number: sg.number } : {}),
        ...(sg.hermannMauguin !== undefined ? { hermannMauguin: sg.hermannMauguin } : {}),
        ...(options.hall !== undefined ? { hall: options.hall } : {}),
        ...(options.setting !== undefined ? { setting: options.setting } : {}),
      },
      cell,
    ),
  );
}
