/**
 * Built-in space-group engine: turn a space-group *number or Hermann–Mauguin
 * symbol* into its full operation list by closing a small set of generators,
 * instead of depending on a CIF to enumerate every equivalent position.
 *
 * Why this exists (Roadmap F2). The symmetry-constraint machinery
 * (`siteConstraints`, `adpConstraints`, `allowedMoments`, `cellConstraints`) is
 * correct but is only ever as good as the operation list it is handed. When that
 * list comes straight from a CIF it may be incomplete, non-standard, or absent —
 * so the constraints derived from it inherit those gaps. A generator-based engine
 * gives a *canonical, complete* operation set keyed by the International Tables
 * number, which is the trustworthy foundation robust refinement needs.
 *
 * Theory. A space group is generated by a handful of operations; composing them
 * (and their products) until no new operation appears yields the whole group —
 * the standard orbit/closure construction. Centring translations are ordinary
 * generators here (rotation = I, translation = the centring vector), so an
 * F-centred group is just its point-group cosets × the four centring cosets.
 *
 * Scope. This module seeds a small, individually verified table (triclinic
 * through cubic, including the F-4̄3m of the bundled GaNb₄Se₈ data). Full
 * 230-group coverage, Wyckoff-position enumeration, and setting/origin transforms
 * are later F2 increments; the closure engine and the table format here are what
 * they build on.
 */

import type { SpaceGroup, SymmetryOperation } from "@/core/crystal/types";
import type { Vec3 } from "@/core/math/types";
import { composeOperations, operationKey, parseSymmetryOperation } from "@/core/crystal/symmetry";
import { wrapFractional } from "@/core/math/vec3";

/** A hard cap on closure size: no standard space group exceeds 192 general
 *  positions, so overshooting means the generators are wrong (or non-crystallo-
 *  graphic) and we should fail loudly rather than loop forever. */
const MAX_GROUP_ORDER = 768;

const IDENTITY: SymmetryOperation = parseSymmetryOperation("x,y,z");

/** Wrap an operation's translation into [0, 1) so equal cosets share a key. */
function normalizeTranslation(op: SymmetryOperation): SymmetryOperation {
  return { ...op, translation: wrapFractional(op.translation) };
}

/**
 * Close a set of generators into the full group: seed with the identity and the
 * generators, then repeatedly compose every pair until the set stops growing.
 * Operations are deduplicated modulo lattice translation via `operationKey`.
 * Throws if the set exceeds {@link MAX_GROUP_ORDER} (a sign of bad generators).
 *
 * Idempotent on an already-complete group: closing a full operation list returns
 * an equivalent full list.
 */
export function expandGenerators(
  generators: readonly SymmetryOperation[],
  maxOrder: number = MAX_GROUP_ORDER,
): SymmetryOperation[] {
  const byKey = new Map<string, SymmetryOperation>();
  byKey.set(operationKey(IDENTITY), IDENTITY);
  for (const g of generators) {
    const n = normalizeTranslation(g);
    byKey.set(operationKey(n), n);
  }

  let changed = true;
  while (changed) {
    changed = false;
    const current = [...byKey.values()];
    for (const a of current) {
      for (const b of current) {
        const c = composeOperations(a, b);
        const key = operationKey(c);
        if (!byKey.has(key)) {
          byKey.set(key, c);
          changed = true;
          if (byKey.size > maxOrder) {
            throw new Error(
              `Group closure exceeded ${maxOrder} operations — generators are likely invalid.`,
            );
          }
        }
      }
    }
  }
  return [...byKey.values()];
}

/** One entry in the built-in generator table. */
interface SpaceGroupEntry {
  readonly number: number;
  readonly hermannMauguin: string;
  /** Jones-Faithful generator strings (identity is implicit). Centring vectors
   *  are included as pure-translation generators. */
  readonly generators: readonly string[];
  /** Extra lookup spellings (e.g. the compact "P21/c" for "P 1 21/c 1"). */
  readonly aliases?: readonly string[];
}

/**
 * Verified generator table. Each entry is validated in `spaceGroups.test.ts` by
 * its known general-position multiplicity (the group order) and the closure
 * property; F-4̄3m is additionally matched operation-for-operation against the
 * real GaNb₄Se₈ CIF.
 *
 * Cubic generators: {2[001], 3[111]} → T (12); +σd(y,x,z) → T_d (24, no
 * inversion) for F-4̄3m; {4[001], 3[111]} → O (24); +1̄ → O_h (48) for Fm-3̄m;
 * each × the four F-centring cosets.
 */
const ENTRIES: readonly SpaceGroupEntry[] = [
  { number: 1, hermannMauguin: "P 1", generators: [] },
  { number: 2, hermannMauguin: "P -1", generators: ["-x,-y,-z"] },
  {
    number: 14,
    hermannMauguin: "P 1 21/c 1",
    generators: ["-x,-y,-z", "-x,y+1/2,-z+1/2"],
    aliases: ["P21/c", "P 21/c"],
  },
  {
    number: 199,
    hermannMauguin: "I 21 3",
    generators: [
      "-x+1/2,-y,z+1/2", // 2₁[001]
      "z,x,y", // 3[111]
      "x+1/2,y+1/2,z+1/2", // I-centring
    ],
    aliases: ["I213", "I2_13"],
  },
  {
    number: 216,
    hermannMauguin: "F -4 3 m",
    generators: [
      "-x,-y,z", // 2[001]
      "z,x,y", // 3[111]
      "y,x,z", // σd
      "x,y+1/2,z+1/2", // F-centring
      "x+1/2,y,z+1/2",
      "x+1/2,y+1/2,z",
    ],
    aliases: ["F-43m"],
  },
  {
    number: 225,
    hermannMauguin: "F m -3 m",
    generators: [
      "-y,x,z", // 4[001]
      "z,x,y", // 3[111]
      "-x,-y,-z", // inversion
      "x,y+1/2,z+1/2", // F-centring
      "x+1/2,y,z+1/2",
      "x+1/2,y+1/2,z",
    ],
    aliases: ["Fm-3m", "Fm3m"],
  },
];

function normalizeSymbol(symbol: string): string {
  return symbol.replace(/\s+/g, "").toLowerCase();
}

const BY_NUMBER = new Map<number, SpaceGroupEntry>(ENTRIES.map((e) => [e.number, e]));
const BY_SYMBOL = new Map<string, SpaceGroupEntry>();
for (const entry of ENTRIES) {
  BY_SYMBOL.set(normalizeSymbol(entry.hermannMauguin), entry);
  for (const alias of entry.aliases ?? []) BY_SYMBOL.set(normalizeSymbol(alias), entry);
}

function lookupEntry(id: number | string): SpaceGroupEntry | undefined {
  return typeof id === "number" ? BY_NUMBER.get(id) : BY_SYMBOL.get(normalizeSymbol(id));
}

/** True if the space group (by number or symbol) is in the built-in table. */
export function isKnownSpaceGroup(id: number | string): boolean {
  return lookupEntry(id) !== undefined;
}

/** The built-in table as `{ number, hermannMauguin }` (for pickers/discovery). */
export function knownSpaceGroups(): { number: number; hermannMauguin: string }[] {
  return ENTRIES.map((e) => ({ number: e.number, hermannMauguin: e.hermannMauguin }));
}

/**
 * Build a complete {@link SpaceGroup} from an International Tables number or a
 * Hermann–Mauguin symbol, by closing the tabulated generators. Throws if the
 * group is not in the built-in table.
 */
export function buildSpaceGroup(id: number | string): SpaceGroup {
  const entry = lookupEntry(id);
  if (!entry) {
    throw new Error(
      `Unknown space group "${id}". Built-in groups: ${ENTRIES.map((e) => `${e.number} (${e.hermannMauguin})`).join(", ")}.`,
    );
  }
  const operations = expandGenerators(entry.generators.map(parseSymmetryOperation));
  return { number: entry.number, hermannMauguin: entry.hermannMauguin, operations };
}

/**
 * Fractional centering translations implied by a Hermann–Mauguin LATTICE letter
 * (the leading symbol character). These are the copies a CIF may leave implicit,
 * listing only the primitive general positions and relying on the letter for the
 * centring — in which case the centring systematic absences (F: h,k,l all even or
 * all odd; I: h+k+l even; C: h+k even; …) would be missed without adding them.
 *
 * A/B/C/I/F are unambiguous. R is deliberately EXCLUDED: its centring exists only
 * in the hexagonal setting, and telling that apart from a primitive rhombohedral
 * setting needs the setting/origin machinery (roadmap F2.4) — adding hexagonal
 * centring blindly would be a physics error in the rhombohedral setting.
 */
export function latticeCenteringTranslations(hermannMauguin: string): Vec3[] {
  const letter = (hermannMauguin.trim().match(/[A-Za-z]/)?.[0] ?? "P").toUpperCase();
  switch (letter) {
    case "A": return [[0, 0.5, 0.5]];
    case "B": return [[0.5, 0, 0.5]];
    case "C": return [[0.5, 0.5, 0]];
    case "I": return [[0.5, 0.5, 0.5]];
    case "F": return [[0, 0.5, 0.5], [0.5, 0, 0.5], [0.5, 0.5, 0]];
    default: return []; // P, R (setting-dependent), or unknown → no centring added
  }
}

/** Format a centring component (0 or ½) as an xyz-string suffix. */
function half(v: number): string {
  return Math.abs(v - 0.5) < 1e-9 ? "+1/2" : "";
}

/** Centering translations as identity-rotation operations (for group closure). */
function centeringOperations(hermannMauguin: string): SymmetryOperation[] {
  return latticeCenteringTranslations(hermannMauguin).map((t) =>
    parseSymmetryOperation(`x${half(t[0])},y${half(t[1])},z${half(t[2])}`),
  );
}

/**
 * Ensure a space group has a complete operation list.
 *
 * - If it already carries operations, close them together with the centring
 *   implied by the Hermann–Mauguin lattice letter (a CIF may list only the
 *   primitive general positions, or only a generating subset). Returns the input
 *   unchanged when already complete, so the original objects/ordering are kept.
 * - If it has no operations but a known number/symbol, build from the table.
 * - Otherwise return it untouched.
 *
 * This never throws: an unknown symbol-only group is returned as-is. It is the
 * safe integration hook for the CIF parser and the structure builders.
 */
export function completeSpaceGroup(sg: SpaceGroup): SpaceGroup {
  if (sg.operations.length > 0) {
    const centering = sg.hermannMauguin ? centeringOperations(sg.hermannMauguin) : [];
    const closed = expandGenerators([...sg.operations, ...centering]);
    return closed.length === sg.operations.length ? sg : { ...sg, operations: closed };
  }
  const id = sg.number ?? sg.hermannMauguin;
  if (id !== undefined && isKnownSpaceGroup(id)) {
    const built = buildSpaceGroup(id);
    const number = sg.number ?? built.number;
    const hermannMauguin = sg.hermannMauguin ?? built.hermannMauguin;
    return {
      operations: built.operations,
      ...(number !== undefined ? { number } : {}),
      ...(hermannMauguin !== undefined ? { hermannMauguin } : {}),
    };
  }
  return sg;
}
