/**
 * Built-in space-group engine: turn a space-group *number or Hermann–Mauguin
 * symbol* into its full operation list by closing a small set of generators,
 * instead of depending on a CIF to enumerate every equivalent position.
 *
 * Why this exists (Roadmap F2). The symmetry-constraint machinery
 * (`siteConstraints`, `adpConstraints`, `allowedMoments`, `cellConstraints`) is
 * correct but is only ever as good as the operation list it is handed. When that
 * list comes straight from a CIF it may be incomplete, non-standard, or absent —
 * so the constraints derived from it inherit those gaps. A generator-based engine
 * gives a *canonical, complete* operation set keyed by the International Tables
 * number, which is the trustworthy foundation robust refinement needs.
 *
 * Theory. A space group is generated by a handful of operations; composing them
 * (and their products) until no new operation appears yields the whole group —
 * the standard orbit/closure construction. Centring translations are ordinary
 * generators here (rotation = I, translation = the centring vector), so an
 * F-centred group is just its point-group cosets × the four centring cosets.
 *
 * Scope. This module seeds a small, individually verified table (triclinic
 * through cubic, including the F-4̄3m of the bundled GaNb₄Se₈ data). Full
 * 230-group coverage, Wyckoff-position enumeration, and setting/origin transforms
 * are later F2 increments; the closure engine and the table format here are what
 * they build on.
 */

import type { SpaceGroup, SymmetryOperation, UnitCell } from "@/core/crystal/types";
import type { Vec3 } from "@/core/math/types";
import { SPACE_GROUP_DATA, type SpaceGroupData } from "@/core/crystal/spaceGroupData";
import { composeOperations, operationKey, parseSymmetryOperation } from "@/core/crystal/symmetry";
import { wrapFractional } from "@/core/math/vec3";

/** A hard cap on closure size: no standard space group exceeds 192 general
 *  positions, so overshooting means the generators are wrong (or non-crystallo-
 *  graphic) and we should fail loudly rather than loop forever. */
const MAX_GROUP_ORDER = 768;

const IDENTITY: SymmetryOperation = parseSymmetryOperation("x,y,z");

/** Wrap an operation's translation into [0, 1) so equal cosets share a key. */
function normalizeTranslation(op: SymmetryOperation): SymmetryOperation {
  return { ...op, translation: wrapFractional(op.translation) };
}

/**
 * Close a set of generators into the full group: seed with the identity and the
 * generators, then repeatedly compose every pair until the set stops growing.
 * Operations are deduplicated modulo lattice translation via `operationKey`.
 * Throws if the set exceeds {@link MAX_GROUP_ORDER} (a sign of bad generators).
 *
 * Idempotent on an already-complete group: closing a full operation list returns
 * an equivalent full list.
 */
export function expandGenerators(
  generators: readonly SymmetryOperation[],
  maxOrder: number = MAX_GROUP_ORDER,
): SymmetryOperation[] {
  const byKey = new Map<string, SymmetryOperation>();
  byKey.set(operationKey(IDENTITY), IDENTITY);
  for (const g of generators) {
    const n = normalizeTranslation(g);
    byKey.set(operationKey(n), n);
  }

  let changed = true;
  while (changed) {
    changed = false;
    const current = [...byKey.values()];
    for (const a of current) {
      for (const b of current) {
        const c = composeOperations(a, b);
        const key = operationKey(c);
        if (!byKey.has(key)) {
          byKey.set(key, c);
          changed = true;
          if (byKey.size > maxOrder) {
            throw new Error(
              `Group closure exceeded ${maxOrder} operations — generators are likely invalid.`,
            );
          }
        }
      }
    }
  }
  return [...byKey.values()];
}

/** Normalize a symbol for lookup: drop whitespace, lowercase. */
function normalizeSymbol(symbol: string): string {
  return symbol.replace(/\s+/g, "").toLowerCase();
}
/** Compact a full H-M symbol by dropping the "1" axis placeholders (so the full
 *  monoclinic "P 1 21/c 1" also answers to the common short "P21/c"). */
function compactSymbol(hm: string): string {
  return hm.split(/\s+/).filter((t) => t !== "1").join("");
}

const BY_NUMBER = new Map<number, SpaceGroupData>(SPACE_GROUP_DATA.map((e) => [e.number, e]));
const BY_SYMBOL = new Map<string, SpaceGroupData>();
function addSymbol(key: string, data: SpaceGroupData): void {
  if (key && !BY_SYMBOL.has(key)) BY_SYMBOL.set(key, data); // first wins → no alias clobbers a canonical symbol
}
// Exact spellings first, then bar-dropped fallbacks (e.g. "Fm3m" for "Fm-3m"),
// added only where they do not collide with a canonical symbol (so "P3"/"P-3"
// stay distinct).
for (const e of SPACE_GROUP_DATA) {
  addSymbol(normalizeSymbol(e.hm), e);
  addSymbol(normalizeSymbol(compactSymbol(e.hm)), e);
}
for (const e of SPACE_GROUP_DATA) {
  addSymbol(normalizeSymbol(e.hm).replace(/-/g, ""), e);
  addSymbol(normalizeSymbol(compactSymbol(e.hm)).replace(/-/g, ""), e);
}

function lookupEntry(id: number | string): SpaceGroupData | undefined {
  if (typeof id === "number") return BY_NUMBER.get(id);
  const n = normalizeSymbol(id);
  return BY_SYMBOL.get(n) ?? BY_SYMBOL.get(n.replace(/-/g, ""));
}

/** True if the space group (by number or symbol) is in the built-in table. */
export function isKnownSpaceGroup(id: number | string): boolean {
  return lookupEntry(id) !== undefined;
}

/** The built-in table as `{ number, hermannMauguin }` (for pickers/discovery). */
export function knownSpaceGroups(): { number: number; hermannMauguin: string }[] {
  return SPACE_GROUP_DATA.map((e) => ({ number: e.number, hermannMauguin: e.hm }));
}

/**
 * Build a {@link SpaceGroup} from an International Tables number or a
 * Hermann–Mauguin symbol, using the generated 230-group table (standard
 * settings). Throws if the symbol/number is not recognized.
 */
export function buildSpaceGroup(id: number | string): SpaceGroup {
  const entry = lookupEntry(id);
  if (!entry) {
    throw new Error(`Unknown space group "${id}". Expected an IT number 1–230 or a standard Hermann–Mauguin symbol.`);
  }
  return {
    number: entry.number,
    hermannMauguin: entry.hm,
    operations: entry.ops.map(parseSymmetryOperation),
  };
}

/**
 * Fractional centering translations implied by a Hermann–Mauguin LATTICE letter
 * (the leading symbol character). These are the copies a CIF may leave implicit,
 * listing only the primitive general positions and relying on the letter for the
 * centring — in which case the centring systematic absences (F: h,k,l all even or
 * all odd; I: h+k+l even; C: h+k even; …) would be missed without adding them.
 *
 * A/B/C/I/F are unambiguous. R is deliberately EXCLUDED: its centring exists only
 * in the hexagonal setting, and telling that apart from a primitive rhombohedral
 * setting needs the setting/origin machinery (roadmap F2.4) — adding hexagonal
 * centring blindly would be a physics error in the rhombohedral setting.
 */
export function latticeCenteringTranslations(hermannMauguin: string): Vec3[] {
  const letter = (hermannMauguin.trim().match(/[A-Za-z]/)?.[0] ?? "P").toUpperCase();
  switch (letter) {
    case "A": return [[0, 0.5, 0.5]];
    case "B": return [[0.5, 0, 0.5]];
    case "C": return [[0.5, 0.5, 0]];
    case "I": return [[0.5, 0.5, 0.5]];
    case "F": return [[0, 0.5, 0.5], [0.5, 0, 0.5], [0.5, 0.5, 0]];
    default: return []; // P, R (setting-dependent), or unknown → no centring added
  }
}

/** Format a centring component (0 or ½) as an xyz-string suffix. */
function half(v: number): string {
  return Math.abs(v - 0.5) < 1e-9 ? "+1/2" : "";
}

/** Centering translations as identity-rotation operations (for group closure). */
function centeringOperations(hermannMauguin: string): SymmetryOperation[] {
  return latticeCenteringTranslations(hermannMauguin).map((t) =>
    parseSymmetryOperation(`x${half(t[0])},y${half(t[1])},z${half(t[2])}`),
  );
}

/**
 * Obverse R-centring operations, but ONLY when the cell is in the HEXAGONAL
 * setting (a=b, α=β=90°, γ=120°). An R group in the primitive rhombohedral
 * setting (a=b=c, α=β=γ) has no centring — which is why F2.2 could not add R
 * centring from the symbol alone; the cell resolves the setting.
 */
function rhombohedralHexCenteringOps(hermannMauguin: string, cell: UnitCell): SymmetryOperation[] {
  const letter = (hermannMauguin.trim().match(/[A-Za-z]/)?.[0] ?? "P").toUpperCase();
  const hexSetting = Math.abs(cell.gamma - 120) < 1 && Math.abs(cell.alpha - 90) < 1 && Math.abs(cell.beta - 90) < 1;
  if (letter !== "R" || !hexSetting) return [];
  return ["x+2/3,y+1/3,z+1/3", "x+1/3,y+2/3,z+2/3"].map(parseSymmetryOperation);
}

/**
 * Ensure a space group has a complete operation list.
 *
 * - If it already carries operations, close them together with the centring
 *   implied by the Hermann–Mauguin lattice letter (a CIF may list only the
 *   primitive general positions, or only a generating subset). Returns the input
 *   unchanged when already complete, so the original objects/ordering are kept.
 * - If it has no operations but a known number/symbol, build from the table.
 * - Otherwise return it untouched.
 *
 * This never throws: an unknown symbol-only group is returned as-is. It is the
 * safe integration hook for the CIF parser and the structure builders.
 */
export function completeSpaceGroup(sg: SpaceGroup, cell?: UnitCell): SpaceGroup {
  if (sg.operations.length > 0) {
    const centering = sg.hermannMauguin
      ? [
          ...centeringOperations(sg.hermannMauguin),
          ...(cell ? rhombohedralHexCenteringOps(sg.hermannMauguin, cell) : []),
        ]
      : [];
    const closed = expandGenerators([...sg.operations, ...centering]);
    return closed.length === sg.operations.length ? sg : { ...sg, operations: closed };
  }
  const id = sg.number ?? sg.hermannMauguin;
  if (id !== undefined && isKnownSpaceGroup(id)) {
    const built = buildSpaceGroup(id);
    const number = sg.number ?? built.number;
    const hermannMauguin = sg.hermannMauguin ?? built.hermannMauguin;
    return {
      operations: built.operations,
      ...(number !== undefined ? { number } : {}),
      ...(hermannMauguin !== undefined ? { hermannMauguin } : {}),
    };
  }
  return sg;
}
